### ISSUE TITLE
create pet post route needs to be debugged

### ISSUE THREAD

**Issue by wonkatin** [Sept-Hackathon-Team8/good-owner#56]
![Screen Shot 2021-10-27 at 11 56 40 AM](https://user-images.githubusercontent.com/33813742/139126063-e47c238e-a9d5-462e-a3a8-1dbfcdfe47d3.png)

**Comment by patgarcia** [comment]
This could have been an issue with the server not running locally. Have you encountered this error again?

If you encounter it again, click on the server address--`http://localhost:8000/api/pets`  in this case, because that `400` is signaling it couldn't reach the server.

**Comment by sirkittles** [comment]
<img width="667" alt="Screen Shot 2021-11-03 at 11 15 55 AM" src="https://user-images.githubusercontent.com/61197578/140088630-777e916c-fefb-49ff-b82c-5528dfe7e31c.png">

**Comment by sirkittles** [comment]
I'm having a similar issue with Sarah I believe. It's giving me unauthorized and bad requests. Once again having that issue where home is just showing loading data
