### ISSUE TITLE
Tips Text Alignment 

### ISSUE THREAD

**Issue by winnerwill711** [Sept-Hackathon-Team8/good-owner#62]
We want the tips screen to have a more narrow text field like the task screens. We would also like the grey box in the back, and the bullet points. The top is what is currently there, the bottom is what we designed.

![Screen Shot 2021-11-03 at 12 27 17 PM](https://user-images.githubusercontent.com/92542537/140101862-26b6a8db-c3c7-42ce-b751-6ca65035d4b0.png)

![Try Again 2 0](https://user-images.githubusercontent.com/92542537/140102107-ec072f56-476e-48fc-9538-610f7bb504b9.png)

**Comment by wonkatin** [comment]
I fixed this but the live site has not been updated
![Screen Shot 2021-11-03 at 11 31 49 AM](https://user-images.githubusercontent.com/33813742/140102652-d113a598-b7cc-4542-82aa-0d34f2095a7c.png)
